#!/usr/bin/env python

import sys

def bytes_from_file(filename, chunksize=8192):
    with open(filename, "rb") as f:
        while True:
            chunk = f.read(chunksize)
            if chunk:
                for b in chunk:
                    yield b
            else:
                break

newlines = 0
size = 32
if len(sys.argv) < 2:
    print("please enter file name")
    exit(1)
name = sys.argv[1][:-4].capitalize()
res = "constexpr core::ConstPaletteSprite<32, 32, CharPalette> "+name+" {\n"
res += '    "'
i = 0

#this assumes the image is 32x32 and made by gimp, which is reasonable
for b in bytes_from_file(sys.argv[1]):
    if newlines < 4:
        if b == ord('\n'):
            #print("NEWLINE")
            newlines +=1
        continue
    i += 1
    if b == 0: res += "."
    elif b == 0x30: res += '1'
    elif b == 0x7f: res += '2'
    elif b == 0xff: res += '0'
    else:
        print("unrecognized", b)
        break
    if i >= size:
        i = 0
        res += '",\n    "'
res = res[:-5] + "};"
print(res)
# print("nl", newlines)
# print("str", str[:-2])
